- alias: 'Welcome Home'
  id: '1508212445583'
  trigger:
    entity_id: sensor.front_door_open
    from: Closed
    platform: state
    to: Open
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: '{{is_state("device_tracker.ryan_pixel", "home") and as_timestamp(now()) - as_timestamp(states.device_tracker.ryan_pixel.last_changed) < 900}}'
      - condition: template
        value_template: '{{ not is_state("device_tracker.ryan_pixel", "home")}}'  
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.apartment
        volume_level: 0.5
    - service: tts.amazon_polly_b_say
      data_template:
        entity_id: media_player.apartment
        message: >
          <speak>
            <prosody pitch='-20%'> 
              <amazon:effect vocal-tract-length='+20%'> 
                Welcome home!
                {% if states.sun.sun.attributes.elevation < 3.5 %}
                  It was pretty dark in here, so I turned on the lights.
                {% endif %}
                The current time is {{ now().strftime('%I:%M %p') }}.
              </amazon:effect>
            </prosody>
          </speak>
        cache: false
    - condition: numeric_state
      below: '3.5'
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
    - service: scene.turn_on
      data:
        entity_id: scene.normal_lighting

- alias: Harmony
  hide_entity: True
  trigger:
  - platform: state
    entity_id: input_select.harmony
    from: 'Select Activity'
  action:
  - service: remote.turn_on
    entity_id: remote.living_room
    data_template:
      activity: >
        {% if is_state("input_select.harmony", "Watch TV") %}
          22853421
        {% elif is_state("input_select.harmony", "Play Xbox 360") %}
          28993774
        {% elif is_state("input_select.harmony", "Play PS4") %}
          28993836
        {% elif is_state("input_select.harmony", "Play Switch") %}
          28993872
        {% else %}
        {% endif %}
  - service: input_select.select_option
    entity_id: input_select.harmony
    data_template:
      option: "Select Activity"
      
- alias: Harmony Off
  hide_entity: True
  trigger:
  - platform: state
    entity_id: input_select.harmony
    to: 'Power Off'
  action:
  - service: remote.turn_off
    entity_id: remote.living_room
  - service: input_select.select_option
    entity_id: input_select.harmony
    data_template:
      option: "Select Activity"
      
- alias: STOP Streaming Radio on CHROMECAST
  trigger:
    - platform: state
      entity_id: input_select.radio_station
      to: "None"
  action:
    service: media_player.turn_off
    data_template:
      entity_id: >
          {% if is_state("input_select.radio_player", "Living Room") %}
            media_player.tv
          {%-elif is_state("input_select.radio_player", "Kitchen") %}
            media_player.kitchen_home
          {%-elif is_state("input_select.radio_player", "Bedroom") %}
            media_player.bedroom_speaker
          {%-elif is_state("input_select.radio_player", "All") %}
            media_player.apartment
          {% else %}
            "None"
          {% endif %}

- alias: START Streaming Radio on CHROMECAST
  trigger:
    - platform: state
      entity_id: input_select.radio_station
  action:
    - service: media_player.play_media
      data_template:
        entity_id: >
          {% if is_state("input_select.radio_player", "Living Room") %}
            media_player.tv
          {%-elif is_state("input_select.radio_player", "Kitchen") %}
            media_player.kitchen_home
          {%-elif is_state("input_select.radio_player", "Bedroom") %}
            media_player.bedroom_speaker
          {%-elif is_state("input_select.radio_player", "All") %}
            media_player.apartment
          {% else %}
            "None"
          {% endif %}
        media_content_id: >
          {% if is_state("input_select.radio_station", "90.1 - WABE") %}
            http://pba-ice.streamguys.org/wabe
          {%-elif is_state("input_select.radio_station", "94.1 - Star 94") %}
            https://prod-23-22-55-197.wostreaming.net/entercom-wstrfmaac-ibc1
          {%-elif is_state("input_select.radio_station", "99.7 - Q100") %}
            http://18763.live.streamtheworld.com/WWWQFMAAC.aac
          {%-elif is_state("input_select.radio_station", "ESPN") %}  
            http://edge.espn.cdn.abacast.net/espn-networkmp3-48
          {% else %}
            "None"
          {% endif %}
        media_content_type: 'audio/aac'
        
- alias: Weekday Alarm
  trigger:
    - platform: template
      value_template: '{{ states.sensor.time.state == states.sensor.weekday_alarm_time.state }}'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: media_player.play_media
      data:
        entity_id: media_player.bedroom_speaker
        media_content_id: http://18763.live.streamtheworld.com/WWWQFMAAC.aac
        media_content_type: 'audio/aac'
    - service: media_player.volume_set
      data:
        entity_id: media_player.bedroom_speaker
        volume_level: 0.7
        
- alias: Weekend Alarm
  trigger:
    - platform: template
      value_template: '{{ states.sensor.time.state == states.sensor.weekend_alarm_time.state }}'
  condition:
    condition: time
    weekday:
      - sat
      - sun
  action:
    - service: media_player.play_media
      data:
        entity_id: media_player.bedroom_speaker
        media_content_id: http://18763.live.streamtheworld.com/WWWQFMAAC.aac
        media_content_type: 'audio/aac'
    - service: media_player.volume_set
      data:
        entity_id: media_player.bedroom_speaker
        volume_level: 0.7
