- platform: template
  sensors:
    front_door_open:
      friendly_name: 'Front Door'
      value_template: '{% if is_state("sensor.front_door_sensor_access_control", "23") %}off{% else %}on{% endif %}'
      icon_template: '{% if is_state("sensor.front_door_sensor_access_control", "23") %}mdi:door-closed{% else %}mdi:door-open{% endif %}'
