- platform: template
  sensors:
    front_door_open:
      friendly_name: 'Front Door'
      value_template: '{% if is_state("sensor.hank_hkzwdws01_doorwindow_sensor_access_control_2", "23") %}off{% else %}on{% endif %}'
      icon_template: '{% if is_state("sensor.hank_hkzwdws01_doorwindow_sensor_access_control_2", "23") %}mdi:door-closed{% else %}mdi:door-open{% endif %}'
