homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 289
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
  
zone:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  icon: mdi:home
 
zone 2:
  name: Work
  latitude: !secret latitude_work
  longitude: !secret longitude_work
  icon: mdi:work

frontend:
  themes:
    darkblue:
      primary-color: "#396FB6"
      light-primary-color: "#77a0d4"
      dark-primary-color: "#3539ce"
      text-primary-color: "#ffffff"
      primary-background-color: "#37464f"
      sidebar-text_-_background: "#3c4348"
      paper-card-background-color: "#263137"
      paper-card-header-color: "var(--text-primary-color)"
      secondary-background-color: "var(--primary-background-color)"
      primary-text-color: "var(--text-primary-color)"
      secondary-text-color: "var(--primary-color)"
      paper-listbox-background-color: "var(--sidebar-text_-_background)"
      paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-button-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-bar-color: "var(--dark-primary-color)"
      paper-slider-knob-color: "var(--primary-color)"
      paper-slider-knob-start-color: "var(--primary-color)"
      paper-slider-pin-color: "var(--primary-color)"
      paper-slider-active-color: "var(--primary-color)"
      paper-slider-secondary-color: "var(--light-primary-color)"
      paper-slider-container-color: "var(--sidebar-text_-_background)"
      paper-progress-secondary-color: "var(--sidebar-text_-_background)"
      paper-item-selected_-_background-color: "var(--primary-color)"
      paper-item-icon_-_color: "var(--text-primary-color)"
      paper-item-icon-color: "var(--text-primary-color)"
      paper-item-icon-active-color: "var(--primary-color)"
      paper-grey-50: "var(--sidebar-text_-_background)"
      paper-grey-200: "var(--primary-background-color)"
      label-badge-background-color: "var(--sidebar-text_-_background)"
      label-badge-text-color: "var(--text-primary-color)"
      label-badge-red: "var(--primary-color)"
      label-badge-blue: "var(--light-primary-color)"
      label-badge-green: "var(--dark-primary-color)"
      label-badge-yellow: "var(--text-primary-color)"
      label-badge-grey: "var(--paper-grey-500)"
      table-row-background-color: "var(--paper-card-background-color)"
      table-row-alternative-background-color: "var(--sidebar-text_-_background)"

config:
  
map:

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  trusted_networks:
    - 192.168.1.0/24
  ip_ban_enabled: True
  login_attempts_threshold: 5

updater:

discovery:
  ignore:
    - samsung_tv

#conversation:

history:

logbook:

sun:
  
recorder:
  purge_interval: 2
  purge_keep_days: 5
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - zwave
    entities:
      - sun.sun
      - sensor.date
      - sensor.time
      - sensor.date__time
      - sensor.time__date
      - sensor.time_utc
      - sensor.pws_alerts
      - sensor.pws_weather
      - sensor.pws_weather_1d
      - sensor.pws_weather_1h
      - sensor.pws_weather_2d
      - sensor.weekday_alarm_time
      - sensor.weekend_alarm_time
      - sensor.front_door_sensor_access_control
      - sensor.front_door_sensor_alarm_level
      - sensor.front_door_sensor_alarm_type
      - sensor.front_door_sensor_burglar
      - sensor.front_door_sensor_sourcenodeid

# Text to speech
tts:
  - platform: amazon_polly_b
    aws_access_key_id: !secret poly_aws_access_key_id
    aws_secret_access_key: !secret poly_aws_secret_access_key
    voice: Matthew
    text_type: ssml
  
light:
  platform: hue
  host: 192.168.1.176

nest:
 client_id: !secret nest_client_id
 client_secret: !secret nest_client_secret

remote:
 - platform: harmony
   name: Living Room
   host: 192.168.1.213
   
device_tracker:
 - platform: owntracks_http
   max_gps_accuracy: 600
   
google_assistant:
  project_id: !secret google_assistant_project_id
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  agent_user_id: !secret google_assistant_agent_user_id
  api_key: !secret google_assistant_api_key
  exposed_domains:
     - scene
     - script

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_key

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
input_select: !include input_select.yaml
input_datetime: !include input_datetime.yaml
