homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 289
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
  
zone:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  icon: mdi:home
 
zone 2:
  name: Work
  latitude: !secret latitude_work
  longitude: !secret longitude_work
  icon: mdi:work

frontend:

config:
  
map:

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  trusted_networks:
    - 192.168.1.0/24
  ip_ban_enabled: True
  login_attempts_threshold: 5

updater:

discovery:
  ignore:
    - samsung_tv

#conversation:

history:

logbook:

sun:

# Text to speech
tts:
  - platform: amazon_polly
    aws_access_key_id: !secret poly_aws_access_key_id
    aws_secret_access_key: !secret poly_aws_secret_access_key
    voice: Brian
  
light:
  platform: hue
  host: 192.168.1.176

nest:
 client_id: !secret nest_client_id
 client_secret: !secret nest_client_secret

remote:
 - platform: harmony
   name: Living Room
   activity: 22853421
   
device_tracker:
 - platform: owntracks_http
   max_gps_accuracy: 600
   
google_assistant:
  project_id: !secret google_assistant_project_id
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  exposed_domains:
     - scene

zwave:
  usb_path: /dev/ttyACM0

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
input_select: !include input_select.yaml
