- platform: wunderground
  api_key: !secret wunderground_api_key
  monitored_conditions:
    - alerts
    - weather_1d
    - precip_1d
    - precip_1d_in
    - weather
    - wind_mph
    - wind_dir
    - temp_f
    - feelslike_f
    - weather_1h
    - relative_humidity
    - pressure_in
- platform: template
  sensors:
    harmony_activity:
      friendly_name: 'Current Activity'
      value_template: '{{ states.remote.living_room.attributes.current_activity }}'
    front_door_batt:
      friendly_name: 'Front Door'
      value_template: '{{ states.zwave.front_door.attributes.battery_level }}'
      unit_of_measurement: '%'
