- platform: wunderground
  api_key: !secret wunderground_api_key
  monitored_conditions:
    - alerts
    - weather_1d
    - weather_2d
    - precip_1d
    - precip_2d
    - weather
    - wind_mph
    - temp_f
    - feelslike_f
    - weather_1h
    - relative_humidity
    - temp_high_1d_f
    - temp_high_2d_f
    - temp_low_1d_f
    - temp_low_2d_f
- platform: template
  sensors:
    front_door_open:
      friendly_name: 'Front Door'
      value_template: '{% if is_state("sensor.front_door_sensor_access_control", "23") %}Closed{% else %}Open{% endif %}'
      icon_template: '{% if is_state("sensor.front_door_sensor_access_control", "23") %}mdi:door-closed{% else %}mdi:door-open{% endif %}'
    harmony_activity:
      friendly_name: 'Current Activity'
      value_template: '{{ states.remote.living_room.attributes.current_activity }}'
    weekday_alarm_time:
      friendly_name: 'Weekday Alarm Time'
      value_template: '{{ "%0.02d:%0.02d" | format(states.input_datetime.weekday_alarm_time.attributes.hour | int, states.input_datetime.weekday_alarm_time.attributes.minute | int) }}'
    weekend_alarm_time: 
      friendly_name: 'Weekend Alarm Time'
      value_template: '{{ "%0.02d:%0.02d" | format(states.input_datetime.weekend_alarm_time.attributes.hour | int, states.input_datetime.weekend_alarm_time.attributes.minute | int) }}'
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'
